# Generated by Django 4.2.9 on 2024-02-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rango", "0005_auto_20240204_1550"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="page", name="slug", field=models.SlugField(unique=True),
        ),
    ]
